name: Build Flutter FFI Plugin Example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies for Linux build
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Get dependencies
        run: |
          cd src && mkdir build && cd build
          cmake ..
          make
      - name: Gen dependencies
        run: dart pub get
      - name: Run tests
        run: flutter test
      - name: Get example dependencies
        run: cd example && flutter pub get
      - name: Build Linux
        run: cd example && flutter build linux

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get dependencies
        run: cd example && flutter pub get
      - name: Build Android APK
        run: cd example && flutter build apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get dependencies
        run: cd example && flutter pub get
      - name: Build Windows
        run: cd example && flutter build windows

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get dependencies
        run: cd example && flutter pub get
      - name: Build macOS
        run: cd example && flutter build macos

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get dependencies
        run: cd example && flutter pub get
      - name: Build iOS (no code sign)
        run: cd example && flutter build ios --no-codesign