name: Run Tests
run-name: Unit test🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.4
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: |
          cd src && mkdir build && cd build
          cmake .. && make
      - run: flutter test